version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: banco_teste
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: GlobE
      POSTGRES_DB: energia_glob
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teste-net

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /home/cesar/panda/db
      o: bind

networks:
  teste-net:
    driver: bridge
