version: '3.9'
services:
  postAirDB:
    image: postgres:16
    container_name: postAirDB
    env_file:
      ./variaveis.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airflow

  redis:
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - airflow


  airflow-webserver:
    image: Airflow_Mod:latest
    env_file:
      ./variaveis.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - postAirDB
      - redis
    restart: always
    command: >
      bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver"
    networks:
      - airflow

  airflow-scheduler:
    image: Airflow_Mod:latest
    env_file:
      ./variaveis.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postAirDB
      - redis
    restart: always
    command: scheduler
    networks:
      - airflow

  airflow-worker:
    image: Airflow_Mod:latest
    env_file:
      ./variaveis.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postAirDB
      - redis
    restart: always
    command: celery worker
    networks:
      - airflow

  airflow-init:
    image: Airflow_Mod:latest
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        exec airflow webserver
    env_file:
      -  ./variaveis.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postAirDB
      - redis
    networks:
      - airflow

  
volumes:
  postgres_data_info:
  postgres-data:

networks:
  airflow:
    driver: bridge